#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-${GOOGLE_CLOUD_PROJECT:-zenpulsar}}"
REGION="${REGION:-${GOOGLE_CLOUD_LOCATION:-us-central1}}"
AR_LOCATION="${AR_LOCATION:-${REGION}}"
AR_REPOSITORY="${AR_REPOSITORY:-mutual-spec}"
IMAGE_NAME="${IMAGE_NAME:-mutual-spec-agent}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
IMAGE_URI="${IMAGE_URI:-${AR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}}"
SERVICE_NAME="${CONSOLE_SERVICE_NAME:-mutual-spec-console}"
CONSOLE_RUNTIME_SA="${CONSOLE_RUNTIME_SA:-${CONSOLE_RUNTIME_SERVICE_ACCOUNT:-console-runtime@${PROJECT_ID}.iam.gserviceaccount.com}}"

TELEMETRY_DATASET_ID="${TELEMETRY_DATASET_ID:-telemetry}"
TELEMETRY_LOCATION="${TELEMETRY_LOCATION:-US}"
GCP_ASSET_CHANGES_SUBSCRIPTION="${GCP_ASSET_CHANGES_SUBSCRIPTION:-gcp-all-resource-changes-sub}"
CONSOLE_UPLOAD_DIR="${CONSOLE_UPLOAD_DIR:-/tmp/mutual-spec-console/uploads}"
CONSOLE_ROUTE_REGIONS="${CONSOLE_ROUTE_REGIONS:-us-central1,us-south1,us-east4}"
CONSOLE_MODEL_ZOO="${CONSOLE_MODEL_ZOO:-gemini-3.5-flash,gemini-3.5-flash-strong}"
TRADER_SOURCE_LAYER_CONFIG="${TRADER_SOURCE_LAYER_CONFIG:-config/trader_source_layer.yaml}"
TRADER_RAG_PROVIDER="${TRADER_RAG_PROVIDER:-spanner_rag,mcp}"
GOOGLE_AGENT_SEARCH_ENABLED="${GOOGLE_AGENT_SEARCH_ENABLED:-true}"
TRADER_RAG_MAX_QUERIES="${TRADER_RAG_MAX_QUERIES:-3}"
TRADER_RAG_MAX_RESULTS="${TRADER_RAG_MAX_RESULTS:-5}"
TRADER_RAG_TIMEOUT_SECONDS="${TRADER_RAG_TIMEOUT_SECONDS:-6}"
SPANNER_RAG_INSTANCE_ID="${SPANNER_RAG_INSTANCE_ID:-commodity-rag}"
SPANNER_RAG_DATABASE_ID="${SPANNER_RAG_DATABASE_ID:-trader_rag}"
SPANNER_RAG_DOCUMENTS_TABLE="${SPANNER_RAG_DOCUMENTS_TABLE:-RagDocuments}"
SPANNER_RAG_CHUNKS_TABLE="${SPANNER_RAG_CHUNKS_TABLE:-RagChunks}"
SPANNER_RAG_EMBEDDING_MODEL="${SPANNER_RAG_EMBEDDING_MODEL:-RagEmbeddingModel}"
SPANNER_RAG_GCS_BUCKET="${SPANNER_RAG_GCS_BUCKET:-zenpulsar-spanner-rag-ingest}"
USER_TALKS_RAG_LOG_ENABLED="${USER_TALKS_RAG_LOG_ENABLED:-true}"
USER_TALKS_GCS_BUCKET="${USER_TALKS_GCS_BUCKET:-${SPANNER_RAG_GCS_BUCKET}}"
USER_TALKS_GCS_PREFIX="${USER_TALKS_GCS_PREFIX:-user_talks}"
USER_TALKS_LOCAL_DIR="${USER_TALKS_LOCAL_DIR:-/tmp/mutual-spec-console/user_talks}"
GOOGLE_SEARCH_CX="${GOOGLE_SEARCH_CX:-}"
VERTEX_AI_SEARCH_DATA_STORE_ID="${VERTEX_AI_SEARCH_DATA_STORE_ID:-}"
VERTEX_AI_SEARCH_ENGINE_ID="${VERTEX_AI_SEARCH_ENGINE_ID:-}"
GOOGLE_SEARCH_API_KEY_SECRET="${GOOGLE_SEARCH_API_KEY_SECRET:-}"
MCP_RESEARCH_URL="${MCP_RESEARCH_URL:-}"
MCP_RESEARCH_COMMAND="${MCP_RESEARCH_COMMAND:-python -m opoint_mcp.server}"
MCP_RESEARCH_CWD="${MCP_RESEARCH_CWD:-}"
OPOINT_API_KEY_SECRET="${OPOINT_API_KEY_SECRET:-}"
if [[ -z "${OPOINT_API_KEY_SECRET}" ]] && \
  gcloud secrets versions describe latest \
    --secret=opoint-api-key \
    --project="${PROJECT_ID}" >/dev/null 2>&1; then
  OPOINT_API_KEY_SECRET="opoint-api-key"
fi

SECRET_ARGS=()
if [[ -n "${GOOGLE_SEARCH_API_KEY_SECRET}" ]]; then
  SECRET_ARGS+=(--set-secrets="GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY_SECRET}:latest")
fi
if [[ -n "${OPOINT_API_KEY_SECRET}" ]]; then
  SECRET_ARGS+=(--set-secrets="OPOINT_API_KEY=${OPOINT_API_KEY_SECRET}:latest")
fi

ENV_FILE="$(mktemp)"
trap 'rm -f "${ENV_FILE}"' EXIT
cat >"${ENV_FILE}" <<EOF
GOOGLE_CLOUD_PROJECT: "${PROJECT_ID}"
GOOGLE_CLOUD_LOCATION: "${REGION}"
GOOGLE_GENAI_USE_VERTEXAI: "true"
RESOURCE_REGION_DOMINATION_ENABLED: "true"
RESOURCE_TELEMETRY_COLLECTORS_ENABLED: "true"
TELEMETRY_DATASET_ID: "${TELEMETRY_DATASET_ID}"
TELEMETRY_LOCATION: "${TELEMETRY_LOCATION}"
GCP_ASSET_CHANGES_SUBSCRIPTION: "${GCP_ASSET_CHANGES_SUBSCRIPTION}"
CONSOLE_UPLOAD_DIR: "${CONSOLE_UPLOAD_DIR}"
CONSOLE_ROUTE_REGIONS: "${CONSOLE_ROUTE_REGIONS}"
CONSOLE_MODEL_ZOO: "${CONSOLE_MODEL_ZOO}"
MULTIMODAL_RETRIEVAL_ENABLED: "true"
TRADER_SOURCE_LAYER_CONFIG: "${TRADER_SOURCE_LAYER_CONFIG}"
TRADER_RAG_PROVIDER: "${TRADER_RAG_PROVIDER}"
GOOGLE_AGENT_SEARCH_ENABLED: "${GOOGLE_AGENT_SEARCH_ENABLED}"
TRADER_RAG_MAX_QUERIES: "${TRADER_RAG_MAX_QUERIES}"
TRADER_RAG_MAX_RESULTS: "${TRADER_RAG_MAX_RESULTS}"
TRADER_RAG_TIMEOUT_SECONDS: "${TRADER_RAG_TIMEOUT_SECONDS}"
SPANNER_RAG_INSTANCE_ID: "${SPANNER_RAG_INSTANCE_ID}"
SPANNER_RAG_DATABASE_ID: "${SPANNER_RAG_DATABASE_ID}"
SPANNER_RAG_DOCUMENTS_TABLE: "${SPANNER_RAG_DOCUMENTS_TABLE}"
SPANNER_RAG_CHUNKS_TABLE: "${SPANNER_RAG_CHUNKS_TABLE}"
SPANNER_RAG_EMBEDDING_MODEL: "${SPANNER_RAG_EMBEDDING_MODEL}"
SPANNER_RAG_GCS_BUCKET: "${SPANNER_RAG_GCS_BUCKET}"
USER_TALKS_RAG_LOG_ENABLED: "${USER_TALKS_RAG_LOG_ENABLED}"
USER_TALKS_GCS_BUCKET: "${USER_TALKS_GCS_BUCKET}"
USER_TALKS_GCS_PREFIX: "${USER_TALKS_GCS_PREFIX}"
USER_TALKS_LOCAL_DIR: "${USER_TALKS_LOCAL_DIR}"
GOOGLE_SEARCH_CX: "${GOOGLE_SEARCH_CX}"
VERTEX_AI_SEARCH_DATA_STORE_ID: "${VERTEX_AI_SEARCH_DATA_STORE_ID}"
VERTEX_AI_SEARCH_ENGINE_ID: "${VERTEX_AI_SEARCH_ENGINE_ID}"
MCP_RESEARCH_URL: "${MCP_RESEARCH_URL}"
MCP_RESEARCH_COMMAND: "${MCP_RESEARCH_COMMAND}"
MCP_RESEARCH_CWD: "${MCP_RESEARCH_CWD}"
EOF

gcloud run deploy "${SERVICE_NAME}" \
  --image="${IMAGE_URI}" \
  --region="${REGION}" \
  --project="${PROJECT_ID}" \
  --service-account="${CONSOLE_RUNTIME_SA}" \
  --command="mutual-spec-console" \
  --port=8080 \
  --cpu=1 \
  --memory=1Gi \
  --min-instances=0 \
  --max-instances=3 \
  --allow-unauthenticated \
  --env-vars-file="${ENV_FILE}" \
  "${SECRET_ARGS[@]+"${SECRET_ARGS[@]}"}" \
  --quiet

echo "Console service deployed: ${SERVICE_NAME}"
